api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    exception_to_status:
        App\Application\Orders\Exception\InvalidCheckoutRequestException: 400
        App\Application\Orders\Exception\InsufficientVariantStockException: 409
        App\Application\Orders\Exception\InvalidShippingDestinationException: 422
