name: changelog-tasks

# on:
#   repository_dispatch:
#     types: [trigger-changelog]

# jobs:
#   changelog:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Déclenché par repository_dispatch"
on:
  workflow_run:
    workflows: ["deploy-test"]
    types:
      - completed

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'deploy-test failed'
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'Update the changeLog'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: test         
          fetch-depth: 0 

      - name: Générer une entrée dans CHANGELOG.md
        run: |
          chmod +x .github/workflows/script/generate_changelog.sh
          .github/workflows/script/generate_changelog.sh

      - name: Commit & push le nouveau CHANGELOG.md
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md

          if git diff --cached --quiet; then
            echo "🔹 Aucun changement à committer."
            exit 0
          fi

          git commit -m "🔄 Mise à jour automatique du CHANGELOG"

      - name: Setup Git authentication and push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.APP_TOKEN }}@github.com/${{ github.repository }}
          git push origin test
          git push origin test --tags --force